version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ttrss_user
      - POSTGRES_PASSWORD=ttrss_password
      - POSTGRES_DB=ttrss_db
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    environment:
      - TTRSS_DB_TYPE=pgsql
      - TTRSS_DB_HOST=db
      - TTRSS_DB_PORT=5432
      - TTRSS_DB_NAME=ttrss_db
      - TTRSS_DB_USER=ttrss_user
      - TTRSS_DB_PASS=ttrss_password
      - SELF_URL_PATH=http://192.168.176.22:9999
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - db

  updater:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    environment:
      - TTRSS_DB_TYPE=pgsql
      - TTRSS_DB_HOST=db
      - TTRSS_DB_PORT=5432
      - TTRSS_DB_NAME=ttrss_db
      - TTRSS_DB_USER=ttrss_user
      - TTRSS_DB_PASS=ttrss_password
      - SELF_URL_PATH=http://192.168.176.22:9999
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - app
    command: /opt/tt-rss/updater.sh

  web-nginx:
    image: cthulhoo/ttrss-web-nginx:latest
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app

  qualifyrss:
    image: qualifyrss:latest
    restart: unless-stopped

volumes:
  app:
  backups:
